#!/bin/sh -e

DAEMON="/var/www/rgbled/rgbled.php"
DAEMON_OPTS="-D"
DAEMONUSER="root"
DEAMON_NAME="rgbled.php"

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/var/www/rgbled"

#the below if statement is used to except args for daemon
#if [ "$#" -ne 2 ]; then
    #echo "Set Video to 0"
    #DAEMON_OPTS="-c /root/bin/motion0/motion.conf"
#else
#	if [ "$2" -eq 1 ]; then 
	    #echo "Set Video to 1"
	    #DAEMON_OPTS="-c /root/bin/motion1/motion.conf"
#	else
	    #echo "Set Video to 0"
	    #DAEMON_OPTS="-c /root/bin/motion0/motion.conf"
	
#	fi
#fi

#echo $DAEMON_OPTS

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $DEAMON_NAME Daemon - view /var/log/rgbled.log"
        start-stop-daemon --background --name $DEAMON_NAME --start --user $DAEMONUSER --exec $DAEMON -- $DAEMON_OPTS
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DEAMON_NAME Daemon"
        start-stop-daemon --name $DEAMON_NAME --stop --retry 5 --name $DEAMON_NAME
          log_end_msg $?
}


case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                killall -q $DEAMON_NAME || true
                sleep 2
                killall -q -9 $DEAMON_NAME || true
                ;;

        status)
                status_of_proc "$DEAMON_NAME" "$DAEMON" "system-wide $DEAMON_NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0

